name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: Test
        run: cargo test
      - name: Test without std
        run: cargo test --no-default-features
      - run: cargo fmt --check
      - run: cargo clippy --all-features -- --no-deps -Dwarnings
